// mockData.js
export const instructors = [
  {
    id: 1,
    name: "Rakesh Mehta",
    phone: "9876543210",
    location: "Mumbai",
    availability: "Active",
    experience: "3-5 years",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 2,
    name: "Ishika Mehta",
    phone: "9876543210",
    location: "Mumbai",
    availability: "On Leave",
    experience: "1-3 years",
    profileImage: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: 3,
    name: "Kunal Sharma",
    phone: "9876543210",
    location: "Mumbai",
    availability: "Inactive",
    experience: "Less than 1 year",
    profileImage: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: 4,
    name: "Rakesh Mehta",
    phone: "9876543210",
    location: "Mumbai",
    availability: "Active",
    experience: "3-5 years",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 5,
    name: "Ishika Mehta",
    phone: "9876543210",
    location: "Mumbai",
    availability: "On Leave",
    experience: "1-3 years",
    profileImage: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: 6,
    name: "Kunal Sharma",
    phone: "9876543210",
    location: "Mumbai",
    availability: "Inactive",
    experience: "Less than 1 year",
    profileImage: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: 7,
    name: "Rakesh Mehta",
    phone: "9876543210",
    location: "Mumbai",
    availability: "Active",
    experience: "3-5 years",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 8,
    name: "Ishika Mehta",
    phone: "9876543210",
    location: "Mumbai",
    availability: "On Leave",
    experience: "1-3 years",
    profileImage: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: 9,
    name: "Kunal Sharma",
    phone: "9876543210",
    location: "Mumbai",
    availability: "Inactive",
    experience: "Less than 1 year",
    profileImage: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: 10,
    name: "Rakesh Mehta",
    phone: "9876543210",
    location: "Mumbai",
    availability: "Active",
    experience: "3-5 years",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 11,
    name: "Ishika Mehta",
    phone: "9876543210",
    location: "Mumbai",
    availability: "On Leave",
    experience: "1-3 years",
    profileImage: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: 12,
    name: "Kunal Sharma",
    phone: "9876543210",
    location: "Mumbai",
    availability: "Inactive",
    experience: "Less than 1 year",
    profileImage: "https://randomuser.me/api/portraits/men/3.jpg",
  },

  // Add more instructors as needed
];
